<NewEntityWindow>:
    name: "new_entity"
    entity_name: entity_name
    id_name: id_name
    widget_count : 5
    BaseLayout:
        title: "Entidades"
        MDFloatLayout:
#            PurpleCenteredLabel:
#                text: "Crear nueva entidad"
#                pos_hint:{'center_y': (5/root.widget_count)-coef_y}
            ProgressComponent:
                step: 1
            #
            ScrollView:
                canvas.before:
                    Color:
                        rgba: 0, 1, 0, opacity_coef
                    Line:
                        width: 3
                        rectangle: self.x, self.y, self.width, self.height
                id: new_entity_scrollview
                do_scroll_x: False
                do_scroll_y: True
                size_hint: 1, None
                height: root.height-(root.height*.10)
                pos_hint:{'center_x': 0.5, 'center_y': .37}
                MDGridLayout:
#                    canvas.before:
#                        Color:
#                            rgba: 1, 0, 0, 1
#                        Line:
#                            width: 1
#                            rectangle: self.x, self.y, self.width, self.height
                    id: new_entity_scroll_layout
                    size_hint: 1, None
                    height: 1000 ##
                    cols: 1
                    ##
                    MDFloatLayout:
                        canvas.before:
                            Color:
                                rgba: 1, 0, 0, opacity_coef
                            Line:
                                width: 1
                                rectangle: self.x, self.y, self.width, self.height
                        id: new_entity_float_layout
                        size_hint: 1, None
#                        height: 800
                        height: 900
                        PaddingLayout:
                            size_hint: 1, None
                            height: 60
#                            pos_hint:{'center_x': 0.5, 'center_y': .9}
                            pos_hint:{'center_x': 0.5, 'center_y': .95}
                            ReplicableTextField:
                                id: entity_name
                                copy_to: id_name
                                size_hint_x: 1
                                hint_text: "Nombre de la Organización"
                                helper_text_mode: "on_error"
                        PaddingLayout:
                            size_hint: 1, None
                            height: 60
#                            pos_hint:{'center_x': 0.5, 'center_y': .75}
                            pos_hint:{'center_x': 0.5, 'center_y': .85}
                            MDGridLayout:
                                cols: 2
                                size_hint_x: 1
                                PurpleIconButton:
#                                    canvas.before:
#                                        Color:
#                                            rgba: 0, 0, 1, 1
#                                        Line:
#                                            width: 1
#                                            rectangle: self.x, self.y, self.width, self.height
                                    icon: 'at'
                                    padding: 0, 0, 0, 15
                                OnlyAlphaNumericTextField:
                                    id: id_name
                                    hint_text: "id-nombre-de-la-organización"
                                    helper_text_mode: "on_error"
                        LabelButton:
                            id: more_options_button
                            text: "Más opciones"
#                            pos_hint:{'center_x': 0.5, 'center_y': .6}
                            pos_hint:{'center_x': 0.5, 'center_y': .75}
                            on_release:
                                app.show_more_options(root)
                        ##
                        MDGridLayout:
                            canvas.before:
                                Color:
                                    rgba: 1, 0, 0, opacity_coef
                                Line:
                                    width: 4
                                    rectangle: self.x, self.y, self.width, self.height
                            rows: 5
                            pos_hint:{'center_x': 0.5, 'center_y': .3}
                            size_hint_y: None
                            height: 0
                            opacity: 0
                            id: more_options_container
                            spacing: 0, 20
                            ##
                            PaddingLayout:
                                canvas.before:
                                    Color:
                                        rgba: 0, 1, 1, opacity_coef
                                    Line:
                                        width: 1.2
                                        rectangle: self.x, self.y, self.width, self.height
                                size_hint: 1, None
                                height: 40
                                padding: 19.5, 0, 40, 0
                                MDLabel:
                                    text: "No publicar"
                                    color: app.theme_cls.primary_color
                                MDSwitch:
                                    id: publish_button
                                    active: True
                                    disabled: True
                                    thumb_color: app.theme_cls.primary_color
                                    thumb_color_down: app.theme_cls.bg_darkest

                            PaddingLayout:
                                canvas.before:
                                    Color:
                                        rgba: 0, 1, 1, opacity_coef
                                    Line:
                                        width: 1.2
                                        rectangle: self.x, self.y, self.width, self.height
                                size_hint: 1, None
                                height: 40
                                padding: 19.5, 0, 40, 0
                                MDLabel:
#                                    pos_hint:{'center_x': 0.5, 'center_y': .25}
                                    text: "Crear grupo para miembros"
                                    color: app.theme_cls.primary_color
                                MDSwitch:
                                    id: create_group_button
                                    active: True
                                    disabled: True
                                    thumb_color: app.theme_cls.primary_color
                                    thumb_color_down: app.theme_cls.bg_darkest

                            ScrollView:
                                do_scroll_x: False
                                do_scroll_y: True
                                size_hint: 1, None
                                height: 85
                                PaddingLayout:
                                    size_hint: 1, None
                                    height: 140
                                    MultilineTextField:
                                        id: welcome_message
                                        size_hint_x: 1
                                        size_hint_y: None
                                        hint_text: "Mensaje de bienvenida"
                                        helper_text_mode: "on_error"

                            PaddingLayout:
#                                canvas.before:
#                                    Color:
#                                        rgba: 0, 1, 1, opacity_coef
#                                    Line:
#                                        width: 1.2
#                                        rectangle: self.x, self.y, self.width, self.height
                                size_hint: 1, None
                                height: 40
                                padding: 19.5, 0, 40, 0
                                MDLabel:
                                    text: "Adjuntar áreas disponibles en el mensaje de bienvenida"
                                    color: app.theme_cls.primary_color
                                MDSwitch:
                                    id: add_areas_button
                                    active: True
                                    disabled: True
                                    thumb_color: app.theme_cls.primary_color
                                    thumb_color_down: app.theme_cls.bg_darkest

                            PaddingLayout:
                                canvas.before:
                                    Color:
                                        rgba: 0, 1, 0, opacity_coef
                                    Line:
                                        width: 1.2
                                        rectangle: self.x, self.y, self.width, self.height
                                size_hint_y: None
                                height: 200
                                rows: 2
                                Image:
                                    id: image_thumbnail
                                    source: 'images/thumbnail.png'
#                                    pos_hint:{'center_x': 0.5, 'center_y': .08}
#                                    size_hint: 0.8, 0.4
                                    size_hint_y: None
                                    height: 150
                                    on_touch_down:
                                        app.upload_image(args[1], self)
                                MDLabel:
#                                    pos_hint:{'center_x': 0.5, 'center_y': .25}
                                    halign: "center"
                                    text: "Subir imagen"
                                    color: app.theme_cls.primary_color

                        PurpleButton:
                            id: create_entity_button
                            text: "Siguiente"
                            pos_hint:{'center_x': 0.5, 'center_y': .7}
                            size_hint_x: .4
                            on_release:
                                app.set_entity()
                                root.manager.transition.direction = "left"

