<ValidateWhatsappWindow>:
    name: "validate_whatsapp"
    widget_count : 5
    BaseLayout:
        MDFloatLayout:
            ProgressComponent:
                step: 4
            PurpleCenteredLabel:
                size_hint: 0.8, 0.2
                text: "Escanee este código desde Whatsapp con la opción: \"Whatsapp Web\" "
                pos_hint:{'center_x': .5, 'center_y': (4.3/root.widget_count)-coef_y}
            Image:
                source: 'images/qrcode.png'
                pos_hint:{'center_y': (3.5/root.widget_count)-0.1, 'center_x': .5}
                size_hint: 0.8, 0.4
            PurpleIconButton:
                icon: "refresh-circle"
                user_font_size: "48sp"
                pos_hint:{'center_x': 0.5, 'center_y': (1.7/root.widget_count)-coef_y}
            PurpleButton:
                id: next_button
                text: "Siguiente"
                pos_hint:{'center_x': 0.5, 'center_y': (1/root.widget_count)-coef_y}
                on_release:
                    app.root.current = "share_code"
                    root.manager.transition.direction = "left"
